### ISSUE TITLE
Frequent undefined optList error

### ISSUE THREAD

**Issue by nikmartin** [NYTimes/backbone.stickit#283]
// Backbone.Stickit v0.7.0, MIT Licensed

This happens most frequently when we have a window that opens a new version of itself on the same page. The fact that it cannot reliably be replicated makes me think it may be a timing issue but I have no clue how to debug since window.open thwarts almost all attempts to get a debugger attached.

```
stack: "TypeError: Cannot read property 'opt_labels' of undefined
    at Backbone.Stickit.addHandler.update (/src/vendor/backbone.stickit/backbone.stickit.js:525:25)
    at applyViewFn (/src/vendor/backbone.stickit/backbone.stickit.js:206:66)
    at updateViewBindEl /src/vendor/backbone.stickit/backbone.stickit.js:360:5)
    at _.extend.addBinding (/src/vendor/backbone.stickit/backbone.stickit.js:184:9)
    at null.<anonymous> (/src/vendor/backbone.stickit/backbone.stickit.js:118:16)
    at /src/vendor/lodash/lodash.js:901:23
    at forOwn (/src/vendor/lodash/lodash.js:2105:15)
    at Function.forEach (/src/vendor/lodash/lodash.js:3302:9)
    at _.extend.addBinding (/src/vendor/backbone.stickit/backbone.stickit.js:117:11)
    at _.extend.stickit (/src/vendor/backbone.stickit/backbone.stickit.js:90:12)"
```

**Comment by nikmartin** [comment]
I think we may have this fixed - we are fetching a select list via ajax using a promise and we had an edge case where the wrong model was being accessed. I don't think this an issue with stickit
